name: go_router_examples
description: go_router examples
version: 3.0.1
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '3.38.7'

resolution: workspace

dependencies:
  adaptive_navigation: ^0.0.4
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  go_router_extra_codec_annotation: ^1.1.1
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  json_serializable: ^6.12.0
  go_router_builder: ^4.2.0
  go_router_extra_codec_generator: ^1.1.1

flutter:
  uses-material-design: true