name: go_router_extra_codec_generator
description: A code generator Go Router Extra Codec
version: 1.1.1
repository: https://github.com/hantrungkien/go_router_extra_codec_generator
maintainer: KienHT

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  collection: ^1.19.1
  source_gen: ^4.2.0
  glob: ^2.1.3
  go_router_extra_codec_annotation: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.4

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - deep-linking
  - go-router
  - navigation