name: go_router_extra_codec_annotation
description: A Flutter package that provides annotations for extra codec support in go_router.
version: 1.1.1
repository: https://github.com/hantrungkien/go_router_extra_codec_generator
maintainer: KienHT

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - deep-linking
  - go-router
  - navigation